# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16InyK-9yL5Wyt6fsQERugQBKGa14wVvj
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import statsmodels.api as sm
import matplotlib.pyplot as plt
from sklearn.metrics import mean_squared_error, mean_absolute_error
from statsmodels.stats.outliers_influence import variance_inflation_factor
# %matplotlib inline

from google.colab import files
uploaded = files.upload()  # We Use this to upload 'World Indicators.csv' from our computer

import os
paths_to_try = ['World Indicators.csv', '/mnt/data/World Indicators.csv']
df = None
for p in paths_to_try:
    if os.path.exists(p):
        df = pd.read_csv(p)
        print('Loaded data from', p)
        break

if df is None:
    raise FileNotFoundError('World Indicators.csv not found. Upload it in Colab or place at /mnt/data/World Indicators.csv')

print('Dataset shape:', df.shape)
display(df.head())

print('Missing values per column:')
print(df.isna().sum())
display(df.describe().T)

us = df[df['Country/Region'] == 'United States'][['Year', 'Population Total']].dropna()
us['Year'] = pd.to_numeric(us['Year'], errors='coerce')
us = us.dropna(subset=['Year'])
print('US data rows:', len(us))
display(us.head())

X_us = sm.add_constant(us['Year'])
y_us = us['Population Total']
model_us = sm.OLS(y_us, X_us).fit()
print(model_us.summary())

pred_2015 = model_us.predict([1, 2015])[0]
print('Predicted US population (2015):', pred_2015)

plt.figure(figsize=(8,5))
plt.scatter(us['Year'], us['Population Total'], label='Observed')
plt.plot(us['Year'], model_us.predict(X_us), label='OLS fit', linewidth=2)
plt.xlabel('Year'); plt.ylabel('Population Total'); plt.title('US Population Trend'); plt.legend(); plt.grid(True)
plt.show()

cols = ['Life Expectancy Female','Birth Rate','GDP','Health Exp % GDP','Infant Mortality Rate','Life Expectancy Male']
europe = df[df['Region'] == 'Europe'][cols].copy()
print('Europe rows before dropna:', europe.shape)
europe = europe.dropna()
print('Europe rows after dropna:', europe.shape)
display(europe.head())

import seaborn as sns
plt.figure(figsize=(8,6))
sns.heatmap(europe.corr(), annot=True, fmt='.2f', cmap='coolwarm')
plt.title('Correlation Matrix (Europe)')
plt.show()

X_eu = sm.add_constant(europe.drop(columns=['Life Expectancy Female']))
vif_df = pd.DataFrame({'feature': X_eu.columns,
                       'VIF': [variance_inflation_factor(X_eu.values, i) for i in range(X_eu.shape[1])]})
display(vif_df)

Y = europe['Life Expectancy Female']
X = europe.drop(columns=['Life Expectancy Female'])
X = sm.add_constant(X)
model_eu = sm.OLS(Y, X).fit()
print(model_eu.summary())

preds = model_eu.predict(X)
rmse = np.sqrt(mean_squared_error(Y, preds))
mae = mean_absolute_error(Y, preds)
r2 = model_eu.rsquared
print('RMSE:', rmse); print('MAE:', mae); print('R^2:', r2)

residuals = model_eu.resid
plt.figure(figsize=(8,5))
plt.scatter(preds, residuals); plt.axhline(0, color='red', linestyle='--')
plt.xlabel('Predicted'); plt.ylabel('Residuals'); plt.title('Residuals vs Predicted'); plt.grid(True); plt.show()

sm.qqplot(residuals, line='s'); plt.title('QQ-plot of residuals'); plt.show()

test_input = pd.DataFrame([{
    'const': 1,
    'Birth Rate': 0.03,
    'GDP': 1e9,
    'Health Exp % GDP': 0.04,
    'Infant Mortality Rate': 5,
    'Life Expectancy Male': 80
}])
predicted_life = model_eu.predict(test_input)[0]
print('Predicted Life Expectancy (Female):', round(predicted_life, 2))

from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor(n_estimators=200, random_state=42)
rf.fit(X.drop(columns=['const'], errors='ignore'), Y)
rf_pred = rf.predict(X.drop(columns=['const'], errors='ignore'))
print('RF RMSE:', np.sqrt(mean_squared_error(Y, rf_pred)))

rf_test = pd.DataFrame([{
    'Birth Rate': 0.03,
    'GDP': 1e9,
    'Health Exp % GDP': 0.04,
    'Infant Mortality Rate': 5,
    'Life Expectancy Male': 80
}])
print('RF predicted Life Expectancy (Female):', round(rf.predict(rf_test)[0], 2))

"""# Summary
- US model: [short summary of coefficients and 2015 prediction]
- Europe model: [short summary + metrics (RMSE, MAE, R^2)]
- Diagnostics: [noted issues: VIF, residuals, outliers]
- Recommendations: [clean data, remove outliers, try tree models, cross-validate]*italicized text*
"""